version: '3'

networks:
  app-tier:
    driver: bridge

services:

  jupyter:
    build:
      context: . 
      dockerfile: docs/Dockerfile
    environment:
        - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./.aws:/home/jovyan/.aws
      - ./docs:/home/jovyan/docs:z
      - ./:/home/jovyan/app:z
    ports:
      - "8888:8888"
#    working_dir: "/docs"
    networks:
      - app-tier
#    command: |
#      bash -c "source activate notebook && jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root"

  jupyter-book:
    build:
      context: .
      dockerfile: docs/Dockerfile
    volumes:
      - ./docs:/home/jovyan/docs:z
      - ./:/home/jovyan/app:z
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8001:8001"
    networks:
      - app-tier
#    working_dir: "/docs"
#    command: |
#      bash -c "source activate notebook && python /docs/run_jupyterbook.py"
