name: Docker Build
on: [push]

env:
  PROJECT_SLUG: "aws-parallelcluster-wrapper"
  DOCKER_ORG: "dabbleofdevops"
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  maven-docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Job Environmental Variables 
        run: |
          CALVER="$( date -u '+%Y.%m.%d' )"
          SHA7="${GITHUB_SHA::7}"
          IMAGE_SPEC="${DOCKER_ORG}/${PROJECT_SLUG}:${DOCKER_TAG}"
          echo "CALVER=${CALVER}" >> $GITHUB_ENV
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
          echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV
      - name: Build and Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: ${{env.DOCKER_ORG}}/${{env.PROJECT_SLUG}}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Should this be tag_names?
          tags: "latest, ${{env.CALVER}}, ${{env.DOCKER_TAG}}"
      - name: Test for CLI
        run: |
          docker run --rm -it dabbleofdevops/aws-parallelcluster-wrapper:latest bash -c "aws-parallelcluster-wrapper"